import 'dart:async';

import 'package:audioplayers/audioplayers.dart';
import 'package:buzzer/model/game_cache.dart';
import 'package:buzzer/model/server_settings.dart';
import 'package:buzzer/server/client_detail.dart';
import 'package:buzzer/server/helper.dart';
import 'package:buzzer/server/server_settings.dart';
import 'package:buzzer/util/buzz_state.dart';
import 'package:buzzer/util/widgets.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:buzzer/util/log.dart';
import 'package:flutter_slidable/flutter_slidable.dart';

import '../model/client.dart';
import '../model/message.dart';
import '../model/command.dart';
import '../net/single_multicast.dart';

class BuzzServerScreen extends StatefulWidget {
  const BuzzServerScreen({super.key});

  @override
  State<BuzzServerScreen> createState() => _BuzzServerScreenState();
}

class _BuzzServerScreenState extends State<BuzzServerScreen> {
  final BuzzClients clients = BuzzClients();
  BuzzState state = BuzzState.serverWaitingForClients;
  String myIP = "";
  String myWifi = "";
  bool created = false;
  int roundSecondsRemaining = 10;
  bool roundStarted = false;
  late DateTime roundStartTime;
  Timer? roundTimer;
  Timer? multicastTimer;
  final audioPlayer = AudioPlayer();
  bool serverAlive = false;
  ServerSettings settings = ServerSettings();

  @override
  void initState() {
    Log.log('Server InitState');
    startMulticastTimer();

    StaticSingleMultiCast.controller2.stream.listen((BuzzMsg msg) {
      // Assert that there is no cross talk.
      if (msg.source == BuzzCmd.server) {
        // Our own message
        return;
      }

      // Messages from a particular client
      BuzzClient? client = clients.findById(msg.sourceId);

      // Race condition
      // Client has an id but server has not processed the registration
      //    to create a client card.
      if (client != null) {
        onClientMessage(msg, client);
        return;
      }

      // Here we process and create a new client card.
      assert(msg.cmd == BuzzCmd.newClientRequest);
      processNewClient(msg);
    });

    super.initState();
  }

  ///////////////////////////////////////////////////////////////////
  ///
  Future processNewClient(
    BuzzMsg msg,
  ) async {
    assert(msg.cmd == BuzzCmd.newClientRequest);
    // ID is generated by the client - so that we can use the same id to send
    final String id = msg.sourceId;
    String name = await GameCache.addNewClient(id);

    // Successful add of new client.
    // Create a new client card.
    setState(() {
      clients.add(name, id);
    });

    // return new server-assigned name
    final BuzzMsg ncResponse = BuzzMsg(
        BuzzCmd.server, BuzzCmd.newClientResponse, {"name": name},
        targetId: id);

    Log.log(ncResponse.toSocketMsg());
    StaticSingleMultiCast.sendBuzzMsg(ncResponse);
    GameCache.dump();
  }

  @override
  void dispose() {
    stopRoundTimer();
    stopMulticastTimer();
    audioPlayer.dispose();
    super.dispose();
  }

  ///////////////////////////////////////////
  // UI
  //
  @override
  Widget build(BuildContext context) {
    final appBar = AppBar(
      leading: WIDGETS.heartbeatIcon(serverAlive),
      title: WIDGETS.appBarTitle(name: "நடுவர்"),
    );

    final availableHt =
        MediaQuery.of(context).size.height - appBar.preferredSize.height;
    final topPanelHeight = availableHt * 0.75;
    final topPanelWidth = MediaQuery.of(context).size.width;

    return WillPopScope(
        onWillPop: () async {
          // TODO - close multicast
          return true;
        },
        child: Scaffold(
            appBar: appBar, body: buildBody(topPanelWidth, topPanelHeight)));
  }

  Widget buildBody(w, h) {
    return Column(children: [
      Padding(
        padding: const EdgeInsets.all(8.0),
        child: SizedBox(
          width: w,
          height: h,
          child: buildClients(),
        ),
      ),
      const Divider(
        height: 5,
        color: Colors.grey,
      ),
      Padding(
        padding: const EdgeInsets.all(8.0),
        child: buildStatus(),
      )
    ]);
  }

  Widget buildClients() {
    final count = clients.length;
    if (count == 0) {
      // Waiting for clients.
      return Center(child: WIDGETS.waitingForClients());
    }

    if (settings.viewMode == "grid") {
      return GridView.builder(
          itemCount: clients.length,
          gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 3,
            childAspectRatio: 1.75,
          ),
          itemBuilder: (context, int index) {
            BuzzClient client = clients.clients[index];
            // todo - call buildServer
            return GestureDetector(
                onTap: () => {
                      Navigator.push(
                          context,
                          MaterialPageRoute(
                              builder: (context) =>
                                  ClientDetail(client, index)))
                    },
                child: buildGridClient(client, index));
          });
    }

    return ListView.builder(
      itemCount: clients.length,
      itemBuilder: (context, int index) {
        BuzzClient client = clients.clients[index];
        // todo - call buildServer
        return GestureDetector(
            onTap: () => {
                  Navigator.push(
                      context,
                      MaterialPageRoute(
                          builder: (context) => ClientDetail(client, index)))
                },
            child: buildSlidableClient(client, index));
      },
    );
  }

  //////////////////////////////////////
  //
  Widget buildSlidableClient(client, index) {
    return Slidable(
        endActionPane: ActionPane(
          motion: const DrawerMotion(),
          children: [
            SlidableAction(
                backgroundColor: const Color.fromARGB(255, 199, 152, 152),
                foregroundColor: Colors.white,
                onPressed: (_) => {},
                icon: CupertinoIcons.exclamationmark_circle,
                label: 'Warning'),
            SlidableAction(
                backgroundColor: Colors.redAccent,
                foregroundColor: Colors.white,
                onPressed: (_) => {},
                icon: CupertinoIcons.delete,
                label: 'Delete')
          ],
        ),
        child: ServerHelper.buildClient(
            client, index, sendPingToClient, onClientScoreChange));
  }

  ////////////////////////////////////////////
  ///
  Widget buildGridClient(client, index) {
    final name = Text(client.name, style: const TextStyle(fontSize: 20.0));

    final bell = WIDGETS.bellIconButton(() => sendPingToClient(client),
        hShake: client.bellRinging, vShake: client.bellFlashing);
    final score =
        Text("${client.score}", style: const TextStyle(fontSize: 20.0));

    final row = Padding(
        padding: const EdgeInsets.symmetric(horizontal: 8),
        child: Row(
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [bell, score]));

    final column = Column(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [name, row]);
    final Color color = client.alive ? Colors.greenAccent : Colors.redAccent;
    return Card(
        margin: const EdgeInsets.symmetric(horizontal: 5.0, vertical: 5.0),
        elevation: 10.0,
        shape: Border(left: BorderSide(color: color, width: 5)),
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: column,
        ));
  }

  Widget buildStatus() {
    switch (state) {
      case BuzzState.serverWaitingForClients:
        return handleServerWaitingForClients();
      case BuzzState.clientAreYouReady:
        return Text('Are You Ready: $state');
      case BuzzState.clientReady:
        return Text('Iam Ready: $state');
      default:
        return Text('Bug State: $state');
    }
  }

  ///////////////////////////////////////////////////////
  ///
  Future ringBell(BuzzClient c) async {
    audioPlayer.release();
    AssetSource src = AssetSource("audio/bell.mp3");
    await audioPlayer.play(src);

    setState(() {
      c.bellRinging = true;
    });
    Future.delayed(const Duration(seconds: 1), () {
      setState(() {
        c.bellRinging = false;
      });
    });
  }

  void flashBell(BuzzClient c) {
    setState(() {
      c.bellFlashing = true;
    });
    Future.delayed(const Duration(seconds: 1), () {
      setState(() {
        c.bellFlashing = false;
      });
    });
  }

  ///////////////////////////////////////////////////////
  ///
  startRoundTimer() {
    stopRoundTimer();
    const dur = Duration(seconds: 1);
    roundTimer = Timer.periodic(dur, onRoundTimer);
    setState(() {
      roundStartTime = DateTime.now();
      roundSecondsRemaining = settings.timeoutSeconds;
      Log.log('startRoundTimer remaining:$roundSecondsRemaining');
    });
    onRoundTimer(roundTimer);
  }

  onRoundTimer(_) {
    final now = DateTime.now();
    final duration = now.difference(roundStartTime);
    setState(() {
      roundSecondsRemaining = settings.timeoutSeconds - duration.inSeconds;
      Log.log('onRoundTimer remaining:$roundSecondsRemaining');
      if (roundSecondsRemaining <= 0) {
        onStopRound();
      }
    });
    sendCountdownToAllClients();
  }

  stopRoundTimer() {
    roundTimer?.cancel();
  }

  /////////////////////////////////////////////////////
  ///
  startMulticastTimer() {
    stopMulticastTimer();
    const dur = Duration(seconds: 1);
    multicastTimer = Timer.periodic(dur, onMulticastTimer);
  }

  onMulticastTimer(_) async {
    try {
      // Send heartbeat
      final BuzzMsg hb =
          BuzzMsg(BuzzCmd.server, BuzzCmd.hbq, {}, targetId: 'ALL');
      final int bytes = await StaticSingleMultiCast.sendBuzzMsg(hb);
      if (bytes > 0 && !serverAlive) {
        setState(() {
          serverAlive = true;
        });
      }
    } catch (e) {
      Log.log(e);
      setState(() {
        serverAlive = false;
      });
      stopMulticastTimer(); // Start calls stop?
      startMulticastTimer(); // Start calls stop?
    }

    setState(() {
      clients.performHealthCheck();
    });
  }

  stopMulticastTimer() {
    multicastTimer?.cancel();
  }

  ///////////////////////////////////////////////////////
  ///
  onClientScoreChange(BuzzClient client, int score) {
    setState(() {
      client.score = score;
      sendScoreToClient(client);
    });
  }

  void onStartRound() {
    setState(() {
      roundStarted = true;
    });
    showBuzzerToAllClients();
    startRoundTimer();
  }

  void onStopRound() {
    setState(() {
      roundStarted = false;
    });
    stopRoundTimer();
    sendCountdownToAllClients();
    hideBuzzerToAllClients();
    sendTopBuzzersToAllClients();
  }

  Widget buildStartStop() {
    int groupValue = roundStarted ? 0 : 1;
    return Container(
      alignment: Alignment.center,
      padding: const EdgeInsets.all(10),
      child: CupertinoSlidingSegmentedControl<int>(
        padding: const EdgeInsets.all(8),
        groupValue: groupValue,
        children: const {
          0: Text("Start Round"),
          1: Text("Stop Round"),
        },
        onValueChanged: (value) {
          if (value == 0) {
            onStartRound();
          } else {
            onStopRound();
          }
        },
      ),
    );
  }

  Widget handleServerWaitingForClients() {
    final counts = clients.counts;
    final total = counts[0],
        alive = counts[1],
        dead = counts[2],
        yes = counts[3],
        no = counts[4],
        pending = counts[5];

    Widget statusRow = Row(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          WIDGETS.nameValue("மொத்தம்", "$total"),
          WIDGETS.nameValue("அலைவ்", "$alive"),
          WIDGETS.nameValue("டெட்", "$dead"),
          WIDGETS.nameValue("தெரியும்", "$yes/${settings.buzzedCount}"),
          WIDGETS.nameValue("தெரியாது", "$no"),
          WIDGETS.nameValue("Nota", "$pending"),
        ]);

    final settingsSegue = GestureDetector(
        onTap: () => {
              Navigator.push(
                  context,
                  MaterialPageRoute(
                      builder: (context) => ServerSettingsScreen(settings)))
            },
        child: const Icon(CupertinoIcons.right_chevron));

    Widget actionsRow = Row(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          buildStartStop(),
          WIDGETS.buildCountdownTime(roundSecondsRemaining),
          WIDGETS.button("PING", sendPingToAllClients),
          settingsSegue
        ]);

    final child = Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: <Widget>[
          statusRow,
          const SizedBox(height: 5),
          const Divider(height: 2, thickness: 2),
          const SizedBox(height: 5),
          actionsRow
        ]);

    return Card(
        margin: const EdgeInsets.symmetric(horizontal: 5.0, vertical: 5.0),
        elevation: 10.0,
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: child,
        ));

//    return const Center(child: Text("Connected. Waiting for Clients"));
  }

  /*
  // Process Client messages
  void handleClientMessage(Socket client, BuzzMsg msg) {
    Log.log('From Client: ${msg.toSocketMsg()}');

    BuzzClient? c = clients.findBySocket(client);
    final data = msg.data;

    if (c != null) {
      setState(() {
        c.serverMsg = msg;
      });
      if (msg.cmd == BuzzCmd.lgq) {
        final user = data["user"] ?? "<null>";

        setState(() {
          c.user = user;
          c.updated = DateTime.now();
        });

        // Send login response
        final lgr = BuzzMsg(BuzzCmd.server, BuzzCmd.lgr, {});
        c.sendMessage(lgr);
      } else if (msg.cmd == BuzzCmd.ping) {
        ringBell(c);
        final pong = BuzzMsg(BuzzCmd.server, BuzzCmd.pong, {});
        c.sendMessage(pong);
      } else if (msg.cmd == BuzzCmd.pong) {
        flashBell(c);
      } else if (msg.cmd == BuzzCmd.iAmReady) {
        setState(() {
          c.iAmReady = data["ready"] ?? false;
          c.updated = DateTime.now();
          clients.sortByReadyUpdated();
        });
      } else if (msg.cmd == BuzzCmd.buzzYes || msg.cmd == BuzzCmd.buzzNo) {
        setState(() {
          c.buzzedState = msg.cmd;
          c.updated = DateTime.now();
          clients.sortByBuzzedUpdated();
        });

        final counts = clients.counts;
        final total = counts[0], yes = counts[1], no = counts[2];
        if (total == yes + no) {
          // Round Done.
          onStopRound();
        }
        if (enableBuzzed && yes == buzzedCount) {
          // Round Donw
          onStopRound();
        }
      }
    }
  }

  void handleCloseClient(Socket client) {
    Log.log('Closing Client: ${client.toString()}');
    setState(() {
      clients.remove(client);
    });
  }
  */

  void sendScoreToClient(BuzzClient client) {
    final data = {"score": client.score};
    final score =
        BuzzMsg(BuzzCmd.server, BuzzCmd.score, data, targetId: client.id);
    StaticSingleMultiCast.sendBuzzMsg(score);
  }

  void sendTopBuzzersToAllClients() {
    clients.sortByBuzzedUpdated();

    // Get the top buzzedCount clients.
    final data = clients.getTopBuzzedData(settings.buzzedCount);

    final topBuzzers =
        BuzzMsg(BuzzCmd.server, BuzzCmd.topBuzzers, data, targetId: "ALL");
    StaticSingleMultiCast.sendBuzzMsg(topBuzzers);
  }

  void showBuzzerToAllClients() {
    for (var i = 0; i < clients.length; i++) {
      setState(() {
        clients[i].buzzedState = "";
      });
    }
    final showBuzz =
        BuzzMsg(BuzzCmd.server, BuzzCmd.showBuzz, {}, targetId: 'ALL');
    StaticSingleMultiCast.sendBuzzMsg(showBuzz);
  }

  void hideBuzzerToAllClients() {
    final hideBuzz =
        BuzzMsg(BuzzCmd.server, BuzzCmd.hideBuzz, {}, targetId: 'ALL');
    StaticSingleMultiCast.sendBuzzMsg(hideBuzz);
  }

  void sendCountdownToAllClients() {
    final data = {"sec": roundSecondsRemaining};
    final countdown =
        BuzzMsg(BuzzCmd.server, BuzzCmd.countdown, data, targetId: 'ALL');
    StaticSingleMultiCast.sendBuzzMsg(countdown);
  }

  /*
  //
  void sendAreYouReadyToClient(BuzzClient client) {
    final areYouReady = BuzzMsg(BuzzCmd.server, BuzzCmd.areYouReady, {});
    client.sendMessage(areYouReady);
    setState(() {
      client.buzzedState = "";
      client.iAmReady = false;
      client.updated = DateTime.now();
    });
  }

  void sendAreYouReadyToAllClients() {
    for (var i = 0; i < clients.length; i++) {
      sendAreYouReadyToClient(clients[i]);
    }
  }
  */

  ////////////////////////////////////////////////////////
  ///
  /// Sending client messages
  ///
  void sendPingToClient(BuzzClient client) {
    final ping = BuzzMsg(BuzzCmd.server, BuzzCmd.ping, {}, targetId: client.id);
    StaticSingleMultiCast.sendBuzzMsg(ping);
  }

  void sendPingToAllClients() {
    final ping = BuzzMsg(BuzzCmd.server, BuzzCmd.ping, {}, targetId: 'ALL');
    StaticSingleMultiCast.sendBuzzMsg(ping);
  }

  /////////////////////////////////////////////////////////////////////////
  ///
  /// Receiving client messages
  ///
  Future onClientMessage(BuzzMsg msg, BuzzClient client) async {
    if (msg.cmd == BuzzCmd.hbr) {
      await processHeartbeatResponse(msg);
    }

    if (msg.cmd == BuzzCmd.ping) {
      processPing(client);
    }

    if (msg.cmd == BuzzCmd.pong) {
      // client is responding to a server ping.
      flashBell(client);
    }

    if (msg.cmd == BuzzCmd.rejoinClientRequest) {
      await processRejoinClient(msg);
    }

    Log.log('onClientMessage - complete');
  }

  processPing(client) {
    // Client is pinging server.
    ringBell(client);
    final pong = BuzzMsg(BuzzCmd.server, BuzzCmd.pong, {}, targetId: client.id);
    StaticSingleMultiCast.sendBuzzMsg(pong);
  }

  processHeartbeatResponse(BuzzMsg msg) {
    final String id = msg.sourceId;
    final BuzzClient? client = clients.findById(id);
    assert(client != null);
    client?.updated = DateTime.now();
  }

  processRejoinClient(BuzzMsg msg) {
    assert(msg.cmd == BuzzCmd.rejoinClientRequest);

    final String id = msg.data["id"];
    final String name = msg.data["name"];
    // TODO GameCache.addRejoinClient(id, name);
    GameCache.dump();
  }
}
